# This is a basic workflow to help you get started with Actions

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header
          plugin_introduction: yes
          plugin_topics: yes
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year


